### ISSUE TITLE
Undefined key 'comaction_grade' in the dictionary

### ISSUE THREAD

**Issue by amrheing** [rockaut/check_mk-check_3par#3]
is it possible to implement this?

Check: 3par.vols Vol status - <vol> - The parameter is: ['volstatus_warning': 2 , levels (...), 'compaction_grade', (...) 'volstatus_critical': 3} The variable name is: checkgroup_paramters:3par_volumes

**Comment by rockaut** [comment]
@amrheing should be done now.

**Comment by rockaut** [comment]
solved in e2ab4d0
